public class IntegerException extends Exception {
	String message;
	public  IntegerException(int m) {
		message = "年龄" + m + "不合理";
	
	}
	public String toString() {
		return message;
	}

}
public class People {
  private int age = 1;
  public void setAge(int age) throws IntegerException{
        if(age <= 0|| age >= 160) {
        	throw new IntegerException(age);
        	
        }
        else {
        	this.age = age;
        }
}
	public int  getAge() {
		System.out.println("年龄"+ age + "合理");
		return age;
		
	}

}
public class Example6_5 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
                  People wang = new People();
                  People zhang = new People();
                  try {
                	  wang.setAge(180);
                	  System.out.println(wang.getAge());
                	  
                  }
                	catch (IntegerException e) {
						// TODO: handle exception
                		System.out.println(e.toString());
                		
				  }
                  try {
                	  zhang.setAge(37);
                	  System.out.println(zhang.getAge());
                	  
                  }
                  catch(IntegerException e) {
                	  System.out.println(e.toString());
                  }
                  
	}

}
